#!/bin/bash
if [ -z $2 ]; then 
  echo -e "usage: vm_snamshot [key] vm_name1 vm_name2 ..."
  echo '  -c	 	for create snapshot'
  echo '  -l	 	for load last snapshot'
  echo '  -d	 	for delete last snapshot'
  echo '  --list 	for list snapshots'
  exit 1
fi

host=192.168.121.1
arg=$1
shift

if [[ $arg == -c ]]; then
  for vm_name in $@; do
    echo "create snapshot for $vm_name..."
    ssh root@$host "virsh snapshot-create $vm_name"
    echo "ok"
  done
fi

if [[ $arg == -l ]]; then
  for vm_name in $@; do
    echo "laod snapshot for $vm_name..."
    ssh root@$host "virsh snapshot-revert --domain $vm_name --current"
    echo "ok"
  done
fi

if [[ $arg == -d ]]; then
  for vm_name in $@; do
    echo "delete last snapshot for $vm_name..."
    ssh root@$host "virsh snapshot-delete --domain $vm_name --current"
    echo "ok"
  done
fi

if [[ $arg == --list ]]; then
  for vm_name in $@; do
    echo "list snapshots for $vm_name:"
    ssh root@$host "virsh snapshot-list --domain $vm_name"
  done
fi

